### PR TITLE
update to 2.2.5

### PR DESCRIPTION
**Pull request by avasomething**
Changelog:
- update version, checksum; reset build number
- correct license type
- correct `http` to `https` in URLs

### CODE REVIEW

**Comment by marcoesters** [comment]
Does `toml` need to be `>=5.0` as well? https://github.com/pymssql/pymssql/blob/master/pyproject.toml

I think the links can all be `https` now.

**Review by varlackc — COMMENTED** [review]
we need to use `https` instead of `http` on the `doc_url` and `home` url
https://github.com/AnacondaRecipes/pymssql-feedstock/blob/60769f0b1347669872375b0d033d3ade8189d94b/recipe/meta.yaml#L58&L59

**Comment by avasomething** [comment]
> Does `toml` need to be `>=5.0` as well? https://github.com/pymssql/pymssql/blob/master/pyproject.toml

Nope! That's referring to the `setuptools_scm` package - `toml` versions haven't gotten that high yet.

**Review by marcoesters — APPROVED** [review]
LGTM

**Review by varlackc — APPROVED** [review]
LGTM

**Pull request merged**
